### ISSUE TITLE
Failures Tab Not Available After Adding Gem

### ISSUE THREAD

**Issue by jonmchan** [mhfs/sidekiq-failures#101]
I may be starting sidekiq differently than sidekiq-failures is expecting so it can't hook into sidekiq. I added the gem and restarted my server and I don't see the failures tab. Is there anything I need to add to make sidekiq-failures to properly show up? Here is how I am starting the server:

```
#!/usr/bin/env ruby
require 'sidekiq/web'
app = Sidekiq::Web
app.set :environment, :production
app.set :bind, '0.0.0.0'
app.set :port, 9494
app.run!
```

**Comment by krasnoukhov** [comment]
Can you try adding `require 'sidekiq-failures'`?

**Comment by jonmchan** [comment]
Sweet! That did it! Might want to add a note about ```require 'sidekiq-failures'``` when following any of the standalone instructions in sidekiq (https://github.com/mperham/sidekiq/wiki/Monitoring#standalone).

**Comment by krasnoukhov** [comment]
Well, I'm not sure it's worth noting because it's pretty much basic: you have to require the gem in order to use it.
