### ISSUE TITLE
ActiveJob integration

### ISSUE THREAD

**Issue by dreyks** [mhfs/sidekiq-failures#102]
I moved from plain Sidekiq to ActiveJob backed by Sidekiq, and now my failures tab displays `ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper` as `Worker` and the actual class is burrowed inside Arguments
```
{"job_class"=>"<ACTUAL_CLASS_NAME>", 
"job_id"=>"be4e36fa-4f71-46f9-abd7-d169b89fe0fc",
"queue_name"=>"default", "arguments"=>[]}
```

Maybe it is useful to display the actual class name at least just on the list view?

**Comment by shlima** [comment]
+1

**Comment by krasnoukhov** [comment]
I'd be happy to review and merge a PR that improves this. Thanks

**Comment by dreyks** [comment]
ok I'll look into this when I have some spare time

Sent from my iPhone

On 26 Nov 2015, at 01:25, Dmitry Krasnoukhov <notifications@github.com>
wrote:

I'd be happy to review and merge a PR that improves this. Thanks

—
Reply to this email directly or view it on GitHub
<https://github.com/mhfs/sidekiq-failures/issues/102#issuecomment-159754200>
.

**Comment by dreyks** [comment]
#103
