### ISSUE TITLE
Can't see failed jobs in failures tab

### ISSUE THREAD

**Issue by mulaiko** [mhfs/sidekiq-failures#106]
Hi,

 I just installed your gem. I have a number of failed jobs that where present before I added the gem, after adding the gem I expected to be able to go through the list of said jobs - I currently cannot do this, all I get is text saying "No failed jobs found" please advise on correct setup so that I can view failed jobs in the failures tab.

Cheers

**Comment by mhfs** [comment]
hi @mulaiko, you won't be able to see jobs that failed before you installed the gem. this gem injects a sidekiq middleware that saves the failed jobs to redis.

you check the middleware logic here: https://github.com/mhfs/sidekiq-failures/blob/master/lib/sidekiq/failures/middleware.rb#L4

**Comment by mulaiko** [comment]
@mhfs ok thanks. So any jobs that fail moving forward will be view-able in the failure tab then?

**Comment by mhfs** [comment]
Yup!
