### ISSUE TITLE
Works with Sidekiq v4?

### ISSUE THREAD

**Issue by manuelmeurer** [mhfs/sidekiq-failures#109]
Does it? 😄 
There's [a PR](https://github.com/mhfs/sidekiq-failures/pull/107) adding Sidekiq v4 to the Travis test matrix and those tests fail, but I cannot see if that's because the tests need to be changed or the actual code.

**Comment by mlarraz** [comment]
I finally got the tests passing, but it's kind of hacky. The tests in general are kind of brittle and have too much knowledge of internals.

I've run this gem locally with Sidekiq 4 and seen no problems, plus I see nothing in the code that would be an issue.

**Comment by manuelmeurer** [comment]
Cool thanks, I'll give it a shot!

**Comment by mlarraz** [comment]
Just to add, we rolled this out earlier this week on Sidekiq 4 and have seen no issues.

**Comment by mhfs** [comment]
This has been implemented on #113 which has been merged to master. Please test and I'll cut a release soon. Thanks
