### ISSUE TITLE
Cut a release with the failures fix in

### ISSUE THREAD

**Issue by wjessop** [mhfs/sidekiq-failures#129]
@mcasper Hello, fancy seeing you here! :)

Any chance you could cut a release of the gem? We can use `git:` but an official release would be great.

**Comment by mcasper** [comment]
Oh hey there @wjessop!

Great point, I just pushed up a v1.0.1 tag to the repo, and I'll work on getting Rubygems access to push up an official version

**Comment by wjessop** [comment]
Thanks!

**Comment by mcasper** [comment]
@wjessop Just pushed up 1.0.1 to Rubygems
