### ISSUE TITLE
Retry middleware not instantiated properly.

### ISSUE THREAD

**Issue by MrJoy** [mhfs/sidekiq-failures#139]
```ruby
      def retry_middleware
        @retry_middleware ||=
          Sidekiq::Failures.retry_middleware_class.new
      end
```

This has a problem when the retry middleware class is the default of `Sidekiq::JobRetry`, as that class requires it be constructed with an options hash.  Not sure if this is a recent change to SideKiq or not, but it's definitely the case in SideKiq 6.5.1.

**Comment by fsanggang** [comment]
I am also having this issue. The `options` to `Sidekiq::JobRetry#initialize` became mandatory in this [PR](https://github.com/mperham/sidekiq/pull/5340), [commit](https://github.com/mperham/sidekiq/pull/5340/files#diff-a2a78bd5586e1300341bb91dc8be382aa98126dcde11bd507fe9886d2e643ee7R73).

**Comment by mcasper** [comment]
@MrJoy @fsanggang I've just pushed up v1.0.2 with a fix for this, thanks for reporting it!

**Comment by MrJoy** [comment]
Awesome!  Thank you!
