### ISSUE TITLE
incompatibility with sidekiq_unique_jobs due to safe_relative_time implementation

### ISSUE THREAD

**Issue by fwolfst** [mhfs/sidekiq-failures#148]
Since I do not know which project will react faster and where this is appropriate, I will create [this issue in both repositories](https://github.com/mhenrixon/sidekiq-unique-jobs/issues/790).

`sidekiq_unique_jobs` has a *Locks* Web UI in which current locks are rendered. The page also shows when the lock was created, in a `safe_relative_time`.
`sidekiq-failures` also implements a `safe_relative_times`.
See
https://github.com/mhenrixon/sidekiq-unique-jobs/blob/f381562ba7a57748132ca3e988172f3021997d7c/lib/sidekiq_unique_jobs/web/helpers.rb#L148

and
https://github.com/mhfs/sidekiq-failures/blob/2b30cb1c87ce09cfb1758f90cc720ddf50dcb591/lib/sidekiq/failures/web_extension.rb#L9

However, the implementation in sidekiq_unique_jobs seems to be more robust (surviving `nil` because of a `time.to_s` in `parse_time`), resulting in

![image](https://github.com/mhfs/sidekiq-failures/assets/219373/23efa32f-bfd3-41d7-aa78-f8bd7e278bc6)
 
Now, I am not 100% sure why we have `nil`s here (there is always one weird lock without a timestamp, similar to https://github.com/mhenrixon/sidekiq-unique-jobs/issues/761#issuecomment-1557922059), but if I remove `sidekiq-failures` from the bundle, everything runs fine.

**Comment by darrenterhune** [comment]
This happens with me too, but only when there are sidekiq jobs enqueued and running. If there aren't any enqueued the /sidekiq/locks page functions normally.

**Comment by WvanLelyveld** [comment]
Same here
