### ISSUE TITLE
Internal Server Error on Failures tab

### ISSUE THREAD

**Issue by mahemoff** [mhfs/sidekiq-failures#87]
After upgrading gems, the Failures tab on web UI is giving an Internal Server Error. I notice [someone else](http://stackoverflow.com/questions/23128697/how-to-debug-sidekiq-frontend) is having the same issue. 

Gems:
sidekiq 3.1.3
sidekiq-failures 0.4.2
rails 4.1.1

**Comment by jwoertink** [comment]
I'm getting this error as well. When I try to delete through the web interface, I get `Internal Server Error`. I'm using these three gems together.

```ruby
gem 'sidekiq', '3.3.0'
gem 'sidekiq-failures', '0.4.3'
gem 'sidekiq-history', '0.0.3'
```

I was able to just wipe all the failures out using the `Sidekiq.redis { |c| c.del("failed") }`.

The main issue I'm running into which actually lead me to this thread is

```text
Redis::CommandErrorsidekiq#general
WRONGTYPE Operation against a key holding the wrong kind of value
```

I see some talk about the `sidekiq-benchmark` even though it didn't cause any issues, I'm curious what the idea behind it possibly being issue would be. My thought is that maybe this `sidekiq-history` gem is doing something that is causing this, but I'm not sure what I would look for, or if that's not even a thing.

**Comment by krasnoukhov** [comment]
@jwoertink After you cleaned up old failures, can you reproduce this again? It looks like you might had legacy `failed` key in Redis.

**Comment by jwoertink** [comment]
Yeah, you're right. I cleaned up the old ones, and now I can click the button and it works. I guess it was just a legacy failed key. Still getting the WRONGTYPE error, but I'm not sure what's causing that one though.

**Comment by pawanseerwani** [comment]
Still getting the following error when I try deleting the failed jobs : ERR Operation against a key holding the wrong kind of value

Versions being used.
sidekiq (3.3.2)
sidekiq-failures (0.4.3)
sidekiq-middleware (0.3.0)

Please fix this.

**Comment by amansingla32** [comment]
@pawanseerwani I think, you tried the APIs for sidekiq. I think they too operate on this key as a "sorted set" rather than list. Cleared the failures using this
Sidekiq.redis { |c| c.del("failed") } and it works !

Thanks Dmitry!

**Comment by mberman84** [comment]
I had this same issue. Turns out we upgraded sidekiq but one of my branches was using the old version still, which was causing the issue. Upgrading that branch to the newest version fixed the issue.
