### ISSUE TITLE
Add option to disable retry for failures

### ISSUE THREAD

**Issue by jhilden** [mhfs/sidekiq-failures#92]
Would it be possible to disable the "retry" button for the failures displayed by this gem?  We twice had the problem that a developer thought that all entries in the failures tab need to be retried, while those jobs were already retried automatically and had passed already.

If you don't know exactly what this gem is for, it can be a little confusing.

**Comment by krasnoukhov** [comment]
Hello, thanks for the feedback. I don't feel like this one deserves separate configuration option. As for me, distinction between "Retries" and "Failures" tabs is clear enough. @mhfs, what do you think?

**Comment by jhilden** [comment]
I'm not sure about the solution (configuration options is probably also not nice), just wanted to raise awareness about the issue.

Is there any use case for manually retrying a failure (at least if the worker has not disabled retries)?

**Comment by jhilden** [comment]
a big :+1: from our side

**Comment by mhfs** [comment]
@krasnoukhov this issue age made me realize how long I've been neglecting this project. Sorry guys. Honestly, I haven't been using sidekiq with this gem for years now. I'm no longer suited to provide an opinion. I'm closing and if someone with more familiarity with modern sidekiq wants to consolidate features and provide a PR, it'll be welcome.
