### ISSUE TITLE
The new CSRF protection breaks retry/delete functionality

### ISSUE THREAD

**Issue by JamesChevalier** [mhfs/sidekiq-failures#98]
https://github.com/mperham/sidekiq/blob/master/Changes.md#342

There's a new `csrf_tag` being used throughout the sidekiq web ui now. You can see an example of it in use in the [schedule](https://github.com/mperham/sidekiq/blob/5adbc24cbeef10b05f5737e96bb71e2b0b6d0595/web/views/scheduled.erb#L16) page.

The lack of this tag is causing the site to respond with `Forbidden` instead of retrying/deleting the failed jobs (which I incorrectly reported over in [#1289](https://github.com/mperham/sidekiq/issues/1289)).

I haven't had the chance to test whether there's further setup needed elsewhere in this gem, or if simply including `<%= csrf_tag %>` within the form will resolve the issue. I hope to update this issue later, after I have a chance to test that out.

**Comment by krasnoukhov** [comment]
Thanks for the investigation. I'd be glad to merge your PR if you're up to making one!

**Comment by domness** [comment]
Is this even released?
